### ISSUE TITLE
Custom validator using express-validator

### ISSUE THREAD

**Issue by noisytoken** [bookercodes/booker.codes#6]
I am here after reading your [article](https://booker.codes/input-validation-in-express-with-express-validator/). Your post was great. 

I am creating a custom validator to validate email, and because the async nature validator method always returns undefined. Here is the code:

```
app.use(validator({
    customValidators: {
        isEmailExists: function (param) {
            console.log("isEmail exists");
            // check email already exists or not
            connection.connect();

            var returnVal;

            connection.query('SELECT count(*) as count from feedback where email = ?', [param] , function (error, results, fields) {
                if (error)
                {
                    throw error;
                }
                returnVal = results[0].count ? false: true;
            });
            return returnVal;  // always returns undefined
        }
    }
}));
```

I have been searching desparately but haven't found any solutions to it.

**Comment by bookercodes** [comment]
Sorry, I appreciate you reaching out but I haven't used these technologies in a while, so I'm not sure!

**Comment by bookercodes** [comment]
I would suggest asking on StackOverflow, hopefully someone there can help!
